apiVersion: v2
name: multiple-repos-env10-product7-app1
description: Helm chart for multiple-repos-env10-product7-app1
type: application
version: 0.1.426
appVersion: 1.23.4
maintainers:
  - name: GitOps Team
keywords:
  - application
  - microservice
annotations:
  environment: env10
  product: product7
  application: app1
